// <auto-generated />
using DataAccess.Concrete.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(RecipeContext))]
    [Migration("20220704135506_last")]
    partial class last
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Concrete.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Vegan"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Meat"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Breakfast"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Sea Food"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Detail = "Bir gece önceden suda beklettiğiniz nohutun suyunu süzün ve bir rondonun içine dökün.(Nohutlar haşlanmayacak.)Nohutların üzerine önceden küp küp doğradığınız soğanları, sarımsakları ilave ederek rondoyu bir kez çalıştırın.Ardından doğradığınız maydonozları, taze soğanı ekleyip rondoda karıştırın. Robot malzemeleri çektikten sonra kendiniz de bir spatula yardımıyla mutlaka biraz karıştırın. Karışıma tüm baharatları ve karbonatı da ekleyip tekrar rondoda çekin.Hazırlanan karışımı derin bir kabın içerisine alıp unu ekleyip yoğurun. Hazır olduğunda üzerini bir streç film ile kaplayıp 1 saat buzdolabında bekletin.Bu sırada sosu hazırlamak için süzme yoğurdun içine sarımsağı, tahini, limon suyunu ekleyip güzelce karıştırın.Buzdolabından çıkartttığınız falafel harcından elinizle cevizden küçük parçalar alarak yuvarlayın.Falafel köfteleriniz hazır olduğunda iyice kızdırdığınız yağın içerisine atıp kızartmaya başlayın.Falafelleri kızartırken içlerinin güzelce pişmesi için orta ateşte kızartmaya dikkat edin.Kızarttğınız falafel köftelerini hazırladığınız sos ile birlikte servis edebilirsiniz. Afiyet olsun!",
                            Image = "https://www.nefissyemektarifleri.com/wp-content/uploads/2018/07/falafel-tarifi.jpg",
                            Ingredients = "1,5su bardağı ,nohut(bir gece önceden ıslatılmış),1adet orta boy soğan,2 diş sarımsak,1 çay kaşığı kabartma tozu, 1 çay kaşığı kişniş(arzuya göre),1/4 demet maydanoz,2dal taze soğan,1 çay kaşığı kimyon,1 çay kaşığı tuz,1 çay kaşığı taze çekilmiş tane karabiber,1 çay kaşığı toz kırmızı biber,2 yemek kaşığı un,Kızartmak için:1 su bardağı ayçiçek yağı,Sosu için:1 su bardağı süzme yoğurt,1 yemek kaşığı tahin,2 diş sarımsak ,1yemek kaşığı limon suyu",
                            Title = "Falafel"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Detail = "Biftekleri, ısıttığınız yapışmaz yüzeyli bir tavada mühürleyin. Tereyağını bir tencerede eritin. Piyazlık doğradığınız soğanları ilave edip 3-4 dakika kavurun. Mühürlediğiniz etleri soğanların üzerine alın.Maden suyu, un, salça ve suyu bir kasede pürüzsüz bir kıvam elde edinceye kadar çırpın.Maden sulu harcı bifteklerin üzerine ilave edin.Tuz ve karabiberle tatlandırın.Kısık ateşte 45-50 dakika kadar pişirin.Sıcak servis yapın.",
                            Image = "https://ozhacibeytepeoren.com/wp-content/uploads/2020/03/Dana-Antrikot-350x200.jpg",
                            Ingredients = "600-700 gram kontrfile,5 diş sarımsak,1 adet büyük boy soğan,1 dal taze kekik ,1 dal taze biberiye,4-5 top karabiber,1 yemek kaşığı kırmızı şarap sirkesi,1 tatlı kaşığı worcestershire sos,1 çay kaşığı deniz tuzu,2 yemek kaşığı zeytinyağı,2 yemek kaşığı çiçek yağı",
                            Title = "Steak"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            Detail = "Balıkları temizleyip bol suyla yıkayın. Süzgece alıp suyunu süzün. Balıkların üzerinde bıçakla derin olmayan uzunlamasına kesikler yapın.Soğanları soyup yarım halka şeklinde doğrayın.Maydanozu temizleyip kıyın. ivri biberleri temizleyip ince halkalar şeklinde doğrayın.Sebzeleri bir kaba alın. Üzerine tuz ve karabiber ekleyip harmanlayın. Balıkları limon suyu ve zeytinyağıyla ovun. Balıkları dikdörtgen kesilmiş yağlı kağıtların içine yerleştirin.Üzerine domatesli karışımdan yayıp kağıtların kenarlarını sıkıca kapatın.Önceden ısıtılmış 180 dereceye ayarlı fırında 35-40 dakika pişirin.  Sıcak olarak servis yapın.",
                            Image = "https://www.enpratikbilgiler.com/wp-content/uploads/2020/12/lufer-baligi-nasil-pisirilir-en-kolay-lufer-baligi-pisirme-yontemi-firinda-lufer-tarifi-VBBUiTP9.jpg",
                            Ingredients = "1 kilo lüfer,Sarımsak,Kuru Soğan(kendinize göre artırıp azaltabilirsiniz),3-4 adet orta boy patates,Limon,Zeytinyağı,Tuz",
                            Title = "Fırında Lüfer"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Detail = "Şeker, ılık su ve mayayı yoğurma kabına alıp mayanın aktif hale gelmesini bekleyin.Daha sonra sütü sıvı yağı yumurtayı ve tuzu da ekleyip güzelce karıştırın.Unu azar azar ekleyerek yoğurmaya başlayın. Hamur kıvama geldikten sonra 5-10 dakika daha yoğurun. 15 dakika üzerini nemli bezle kapatarak dinlendirin.Dinlenen hamuru 14 eşit parçaya bölüp bezeler halime getirin. İlk 7’sini alıp tabak büyüklüğünde nişasta kullanarak açın.Her kata eritilmiş tereyağından sürerek üst üst koyun. En üst hamura yağ sürmüyoruz kenara alıp üzerlerini örtün. Kalan 7 beze içinde aynı işlemi yapın.İlk açtığınız 7’li yağlanmış hamuru alıp ellerinizle bastırıp kenarlarından çekiştirerek açın. Açtığınız hamuru 12 eşit parçaya bölüp içlerine birer tatlı kaşığı nutella sürün ve sarın.Yarım saat tepsi mayası için bekleyin. (bu adımı atlamayın lütfen) Yarım saat dolduktan sonra yumurta sarılarını sürüp 200 derece önceden ısıtılmış fırında üzerleri güzelce kızarana kadar pişirin. Yumuşacık harika bir atıştırmalık olacak kolay gelsin",
                            Image = "https://cdn.yemek.com/mncrop/940/625/uploads/2014/10/kruvasan-tarifi.jpg",
                            Ingredients = "1 yemek kaşığı şeker,1 paket yaş maya(kuru maya da olur),1 çay bardağı ılık su,1 su bardağı ılık süt,1 çay bardağı sıvı yağ,1 tane oda sıcaklığında yumurta,1 tatlı kaşığı tuz,4-4, 5 su bardağı un,Hamuru açmak için nişasta,Hamurun aralarına sürmek için eritilmiş tereyağı",
                            Title = "Kruvasan"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Moderator"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@gmail.com",
                            Password = "1234",
                            RoleId = 1,
                            UserName = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "moderator@gmail.com",
                            Password = "1234",
                            RoleId = 2,
                            UserName = "Moderator"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Recipe", b =>
                {
                    b.HasOne("Entities.Concrete.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Concrete.User", b =>
                {
                    b.HasOne("Entities.Concrete.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
